sudo: required
services:
  - docker
language: python
python:
  - "2.7"
  - "3.4"
env:
  matrix:
    - DJANGO_SETTINGS_MODULE=settings.sqlite_only
    - DJANGO_SETTINGS_MODULE=settings.mysql_only
    - DJANGO_SETTINGS_MODULE=settings.postgresql_only
before_script:
  - sudo service docker restart
  - sleep 10
script:
  - ./manage.py db_quick_setup
  - sleep 20
  - docker ps -a
  - if [[ -z "$(docker ps -q)" ]]; then docker logs "$(docker ps -q -n=1)" || true; fi
  - ./manage.py migrate
  - ./manage.py db_quick_setup
